extends: "airbnb"
parser: "babel-eslint"
plugins:
  - react
  - flowtype
  - flow-header
env:
  browser: true
settings:
  import/resolver:
    babel-module:
      extensions:
        - .js
        - .jsx
rules:
  flow-header/flow-header: 2
