pull_request_rules:
  - name: automatic merge when author is zmbush and CI passes
    conditions:
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
      - status-success=codecov/patch
      - status-success=codecov/project
      - author=zmbush
    actions:
      label:
        add:
          - auto-approve
      comment:
        message: Auto-submitting change that passed CI
      merge:
        method: squash
      delete_head_branch:
