trailingComma: 'all'
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: true
printWidth: 100
importOrder:
  - '^react'
  - '^@(mui|material-ui)'
  - '^(components|data|api)'
  - "^\\.\\./"
  - "^\\./"
  - '^/'
importOrderSeparation: true
overrides:
  - files: 'src/**/*.html'
    options:
      printWidth: 140
