trailingComma: 'all'
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: true
printWidth: 100
importOrder:
  - '^firestore'
  - '^@mui'
  - '^utils'
  - '^components'
  - "^\\.\\./"
  - "^\\./"
  - '^/'
importOrderSeparation: true
overrides:
  - files: 'src/**/*.html'
    options:
      printWidth: 140
