[package]
name = "noted"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]

[dependencies]
diesel_codegen = { version = "^0.12", features = ["postgres"] }
diesel = { version = "^0.12", features = ["postgres"] }
dotenv = "^0.10"
env_logger = "^0.4"
iron = "^0.5"
logger = "^0.3"
mount = "^0.3"
ncurses = "5.85.0"
r2d2 = "^0.7"
r2d2-diesel = "^0.12"
router = "^0.5"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
iron-sessionstorage = { version = "^0.6", features = ["redis-backend"] }
handlebars-iron = "^0.24"
params = "^0.6"
oauth2 = { git = "https://github.com/alexcrichton/oauth2-rs.git" }
curl = "*"
