[package]
name = "noted"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
diesel = { version = "1.4.1", features = ["postgres", "r2d2"] }
failure = "0.1.3"
iron = "0.6.0"
log = "0.4.6"
mount = "0.4.0"
noted_db = { path = "./db" }
router = "0.6.0"
serde = "1.0.60"
serde_derive = "1.0"
serde_json = "1.0"
simple_logger = "1.0.1"
staticfile = "0.5.0"
