[package]
name = "noted"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]
edition = "2018"

[workspace]
members = ["db"]

[dependencies]
chrono = "0.4.7"
clap = "2.33.0"
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
failure = "0.1.5"
fern = "0.5.8"
futures = "0.1.28"
gotham = "0.4.0"
gotham_derive = "0.4.0"
http = "0.1.18"
hyper = "0.12.33"
lazy_static = "1.3.0"
log = "0.4.8"
noted_db = { path = "./db" }
r2d2 = "*"
redis = "0.11.0"
serde = "1.0.98"
serde_derive = "1.0.103"
serde_json = "1.0.40"
# simple_logger = "1.2.0"
