[package]
name = "noted"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]
edition = "2018"

[workspace]
members = ["db"]

[dependencies]
clap = "2.33.0"
lazy_static = "1.3.0"
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
failure = "0.1.5"
log = "0.4.6"
noted_db = { path = "./db" }
serde = "1.0.91"
serde_derive = "1.0.90"
serde_json = "1.0.39"
simple_logger = "1.0.1"
gotham = "0.3.0"
gotham_derive = "0.3.0"
futures = "0.1.26"
http = "0.1.17"
hyper = "0.12.28"
r2d2 = "*"
redis = "0.10.0"
