version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  node:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Webpack
          command: npm run build
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/lcov.info
      - store_test_results:
          path: test-results
  rust:
    docker:
      - image: circleci/rust:latest
        environment:
          DATABASE_URL: postgres://noted@localhost:5432/test
          MIGRATION_DIRECTORY: db/migrations
          DIESEL_CONFIG_FILE: db/diesel.toml
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: noted
          POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate Dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{arch}}-{{checksum "Cargo.lock" }}
      - restore_cache:
          keys:
            - kcov-cache-{{arch}}-33
      - restore_cache:
          keys:
            - v4-cargo-bin-cache-{{arch}}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{arch}}-{{checksum "Cargo.lock"}}
      - run:
          name: Install Kcov
          command: ./.circleci/scripts/install-kcov.sh
      - save_cache:
          paths:
            - kcov-33
          key: kcov-cache-{{arch}}-33
      - run:
          name: Install diesel
          command: (cargo install --list | grep 'diesel_cli') || cargo install diesel_cli --no-default-features --features postgres || true
      - save_cache:
          paths:
            - /usr/local/cargo/bin/cargo-kcov
            - /usr/local/cargo/bin/diesel
          key: v4-cargo-bin-cache-{{arch}}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run Migrations
          command: diesel migration run
      - run:
          name: Run all tests
          command: cargo test --all
      - run:
          name: Run kcov
          command: cargo kcov --all --kcov kcov-33/build/src/kcov
      - store_artifacts:
          path: target/cov
      - codecov/upload:
          file: target/cov/kcov-merged/cobertura.xml

workflows:
  version: 2
  build:
    jobs:
      - node
      - rust
