version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  node:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Webpack
          command: npm run build
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/lcov.info
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - node
