version: 2

jobs:
  node:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  rust:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate Dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{arch}}-{{checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{arch}}-{{checksum "Cargo.lock"}}
      - run:
          name: Run all tests
          command: cargo test --all

workflows:
  version: 2
  build:
    jobs:
      - rust
      - node
