// This file is auto-generated by tools/generate_types.js
// Do not modify this file directly!

export interface ErrorData {
  code: number;
  column_name?: string | null;
  constraint_name?: string | null;
  details?: string | null;
  error: string;
  hint?: string | null;
  table_name?: string | null;
}

export interface NewNote {
  body: string;
  parent_note_id?: number | null;
  title: string;
}

export interface NewUserRequest {
  email: string;
  name: string;
  password: string;
}

export interface NoteWithTags {
  archived: boolean;
  body: string;
  created_at: string;
  id: number;
  parent_note_id: number;
  pinned: boolean;
  tags: string[];
  title: string;
  updated_at: string;
  user_id: number;
}

export interface SignIn {
  email: string;
  password: string;
}

export interface UpdateNote {
  archived?: boolean | null;
  body?: string | null;
  parent_note_id?: number | null;
  pinned?: boolean | null;
  title?: string | null;
}

export interface User {
  created_at: string;
  email: string;
  id: number;
  name: string;
  updated_at: string;
}
