// This file is auto-generated by tools/generate_types.js
// Do not modify this file directly!

export interface ErrorData {
  code: number;
  message: string;
  details: string;
  db?: DbErrorDetails | null;
}

export interface DbErrorDetails {
  details?: string | null;
  hint?: string | null;
  table_name?: string | null;
  column_name?: string | null;
  constraint_name?: string | null;
}

export interface NewNotePayload {
  title: string;
  body: string;
  parent_note_id?: number | null;
}

export interface NewUserPayload {
  email: string;
  name: string;
  password: string;
}

export interface NoteWithTags {
  id: number;
  title: string;
  body: string;
  tags: string[];
  created_at: string;
  updated_at: string;
  user_id: number;
  parent_note_id: number;
  archived: boolean;
  pinned: boolean;
}

export interface SignInPayload {
  email: string;
  password: string;
}

export interface UpdateNotePayload {
  title?: string | null;
  body?: string | null;
  parent_note_id?: number | null;
  archived?: boolean | null;
  pinned?: boolean | null;
}

export interface User {
  id: number;
  name: string;
  email: string;
  created_at: string;
  updated_at: string;
}
