[package]
name = "noted_db"
version = "0.1.0"
authors = ["Zach Bush <zach@zmbush.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.13.0"
iron = "0.6.0"
lazy_static = "1.3.0"
serde = "1.0.90"
serde_derive = "1.0.90"
chrono = { version = "0.4.6", features = ["serde"] }
