#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn pretty
(git diff --name-only --cached | grep 'ci/github-actions/ci.yaml') && cargo run --quiet --manifest-path expand-yaml-anchors/Cargo.toml -- generate $PWD && git add .github/workflows
yarn generate-api-types && git add js/data/types.ts
