export const archived: string;
export const card: string;
export const cardContent: string;
export const cardHeader: string;
export const contentRoot: string;
export const loadingSpinner: string;
export const markdown: string;
export const noPrint: string;
export const unlinked: string;
